name: code_review_and_analysis
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  go_router: ^15.2.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  sizer: ^3.0.5
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  flutter_markdown_plus: ^1.0.3
  emoji_picker_flutter: ^4.3.0
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.1
  device_info_plus: ^11.5.0
  flutter_secure_storage: ^9.2.4
  file_picker: ^10.2.0
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  speech_to_text: ^7.1.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
    - assets/animations/mic_animation.json
